export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED'; 

export const REQUEST_KITTYS_PENDING = 'REQUEST_KITTYS_PENDING';
export const REQUEST_KITTYS_SUCCESS = 'REQUEST_KITTYS_SUCCESS';
export const REQUEST_KITTYS_FAILED = 'REQUEST_KITTYS_FAILED'; 